baseURL = 'https://srikur.github.io'
languageCode = 'en-us'
title = "srikur's dev page"
theme = "charaka-hugo-theme"
disqusShortname = ""
relativeURLs = true
preserveTaxonomyNames = true

[services.googleAnalytics]
  ID = ""

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = false
  tabWidth = 4
  noClasses = true
  style = "vulcan" 

[[params.social]]
  url = "about.html"
  fa_icon = "fas fa-info" 

[[params.social]]
  url = "https://github.com/srikur"
  fa_icon = "fab fa-github"

[[params.social]]
  url = "https://www.linkedin.com/in/srikurk/"
  fa_icon = "fab fa-linkedin-in"

[[params.social]]
  url = "https://twitter.com/srikurk"
  fa_icon = "fab fa-twitter"